// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd
{
    /// <summary>
    /// Manages [custom TLS certificates](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#self-signed-untrusted-tls-certificates) used by ArgoCD for connecting Git repositories.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Argocd = Three14.Argocd;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // HTTPS certificate
    ///     var private_git_repository_https = new Argocd.RepositoryCertificate("private-git-repository-https", new()
    ///     {
    ///         Https = new[]
    ///         {
    ///             new Argocd.Inputs.RepositoryCertificateHttpArgs
    ///             {
    ///                 ServerName = "private-git-repository.local",
    ///                 CertData = @"-----BEGIN CERTIFICATE-----\nfoo\nbar\n-----END CERTIFICATE-----
    /// ",
    ///             },
    ///         },
    ///     });
    /// 
    ///     // SSH certificate
    ///     var private_git_repository_ssh = new Argocd.RepositoryCertificate("private-git-repository-ssh", new()
    ///     {
    ///         Sshes = new[]
    ///         {
    ///             new Argocd.Inputs.RepositoryCertificateSshArgs
    ///             {
    ///                 ServerName = "private-git-repository.local",
    ///                 CertSubtype = "ssh-rsa",
    ///                 CertData = @"AAAAB3NzaC1yc2EAAAADAQABAAABgQCiPZAufKgxwRgxP9qy2Gtub0FI8qJGtL8Ldb7KatBeRUQQPn8QK7ZYjzYDvP1GOutFMaQT0rKIqaGImIBsztNCno...
    /// ",
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [ArgocdResourceType("argocd:index/repositoryCertificate:RepositoryCertificate")]
    public partial class RepositoryCertificate : global::Pulumi.CustomResource
    {
        /// <summary>
        /// HTTPS certificate configuration
        /// </summary>
        [Output("https")]
        public Output<ImmutableArray<Outputs.RepositoryCertificateHttp>> Https { get; private set; } = null!;

        /// <summary>
        /// SSH certificate configuration
        /// </summary>
        [Output("sshes")]
        public Output<ImmutableArray<Outputs.RepositoryCertificateSsh>> Sshes { get; private set; } = null!;


        /// <summary>
        /// Create a RepositoryCertificate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositoryCertificate(string name, RepositoryCertificateArgs? args = null, CustomResourceOptions? options = null)
            : base("argocd:index/repositoryCertificate:RepositoryCertificate", name, args ?? new RepositoryCertificateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositoryCertificate(string name, Input<string> id, RepositoryCertificateState? state = null, CustomResourceOptions? options = null)
            : base("argocd:index/repositoryCertificate:RepositoryCertificate", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/Three141/pulumi-argocd/releases/download/v${VERSION}/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositoryCertificate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositoryCertificate Get(string name, Input<string> id, RepositoryCertificateState? state = null, CustomResourceOptions? options = null)
        {
            return new RepositoryCertificate(name, id, state, options);
        }
    }

    public sealed class RepositoryCertificateArgs : global::Pulumi.ResourceArgs
    {
        [Input("https")]
        private InputList<Inputs.RepositoryCertificateHttpArgs>? _https;

        /// <summary>
        /// HTTPS certificate configuration
        /// </summary>
        public InputList<Inputs.RepositoryCertificateHttpArgs> Https
        {
            get => _https ?? (_https = new InputList<Inputs.RepositoryCertificateHttpArgs>());
            set => _https = value;
        }

        [Input("sshes")]
        private InputList<Inputs.RepositoryCertificateSshArgs>? _sshes;

        /// <summary>
        /// SSH certificate configuration
        /// </summary>
        public InputList<Inputs.RepositoryCertificateSshArgs> Sshes
        {
            get => _sshes ?? (_sshes = new InputList<Inputs.RepositoryCertificateSshArgs>());
            set => _sshes = value;
        }

        public RepositoryCertificateArgs()
        {
        }
        public static new RepositoryCertificateArgs Empty => new RepositoryCertificateArgs();
    }

    public sealed class RepositoryCertificateState : global::Pulumi.ResourceArgs
    {
        [Input("https")]
        private InputList<Inputs.RepositoryCertificateHttpGetArgs>? _https;

        /// <summary>
        /// HTTPS certificate configuration
        /// </summary>
        public InputList<Inputs.RepositoryCertificateHttpGetArgs> Https
        {
            get => _https ?? (_https = new InputList<Inputs.RepositoryCertificateHttpGetArgs>());
            set => _https = value;
        }

        [Input("sshes")]
        private InputList<Inputs.RepositoryCertificateSshGetArgs>? _sshes;

        /// <summary>
        /// SSH certificate configuration
        /// </summary>
        public InputList<Inputs.RepositoryCertificateSshGetArgs> Sshes
        {
            get => _sshes ?? (_sshes = new InputList<Inputs.RepositoryCertificateSshGetArgs>());
            set => _sshes = value;
        }

        public RepositoryCertificateState()
        {
        }
        public static new RepositoryCertificateState Empty => new RepositoryCertificateState();
    }
}
