# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_application import *
from .gpg_key import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_argocd.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_argocd.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "argocd",
  "mod": "index/gpgKey",
  "fqn": "pulumi_argocd",
  "classes": {
   "argocd:index/gpgKey:GpgKey": "GpgKey"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "argocd",
  "token": "pulumi:providers:argocd",
  "fqn": "pulumi_argocd",
  "class": "Provider"
 }
]
"""
)
