# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProjectTokenArgs', 'ProjectToken']

@pulumi.input_type
class ProjectTokenArgs:
    def __init__(__self__, *,
                 project: pulumi.Input[_builtins.str],
                 role: pulumi.Input[_builtins.str],
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.str]] = None,
                 renew_after: pulumi.Input[Optional[_builtins.str]] = None,
                 renew_before: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a ProjectToken resource.

        :param pulumi.Input[_builtins.str] project: The project associated with the token.
        :param pulumi.Input[_builtins.str] role: The name of the role in the project associated with the token.
        :param pulumi.Input[_builtins.str] description: Description of the token.
        :param pulumi.Input[_builtins.str] expires_in: Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
        :param pulumi.Input[_builtins.str] renew_after: Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renew_after`. I.e. if `currentDate - issued_at > renew_after`.
        :param pulumi.Input[_builtins.str] renew_before: Duration to control token silent regeneration based on remaining token lifetime. If `expires_in` is set, the provider will regenerate the token if `expires_at - currentDate < renew_before`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
        """
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "role", role)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if expires_in is not None:
            pulumi.set(__self__, "expires_in", expires_in)
        if renew_after is not None:
            pulumi.set(__self__, "renew_after", renew_after)
        if renew_before is not None:
            pulumi.set(__self__, "renew_before", renew_before)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Input[_builtins.str]:
        """
        The project associated with the token.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[_builtins.str]:
        """
        The name of the role in the project associated with the token.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "role", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Description of the token.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="expiresIn")
    def expires_in(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
        """
        return pulumi.get(self, "expires_in")

    @expires_in.setter
    def expires_in(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expires_in", value)

    @_builtins.property
    @pulumi.getter(name="renewAfter")
    def renew_after(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renew_after`. I.e. if `currentDate - issued_at > renew_after`.
        """
        return pulumi.get(self, "renew_after")

    @renew_after.setter
    def renew_after(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "renew_after", value)

    @_builtins.property
    @pulumi.getter(name="renewBefore")
    def renew_before(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Duration to control token silent regeneration based on remaining token lifetime. If `expires_in` is set, the provider will regenerate the token if `expires_at - currentDate < renew_before`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
        """
        return pulumi.get(self, "renew_before")

    @renew_before.setter
    def renew_before(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "renew_before", value)


@pulumi.input_type
class _ProjectTokenState:
    def __init__(__self__, *,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_at: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.str]] = None,
                 issued_at: pulumi.Input[Optional[_builtins.str]] = None,
                 jwt: pulumi.Input[Optional[_builtins.str]] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 renew_after: pulumi.Input[Optional[_builtins.str]] = None,
                 renew_before: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering ProjectToken resources.

        :param pulumi.Input[_builtins.str] description: Description of the token.
        :param pulumi.Input[_builtins.str] expires_at: If `expires_in` is set, Unix timestamp upon which the token will expire.
        :param pulumi.Input[_builtins.str] expires_in: Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
        :param pulumi.Input[_builtins.str] issued_at: Unix timestamp at which the token was issued.
        :param pulumi.Input[_builtins.str] jwt: The raw JWT.
        :param pulumi.Input[_builtins.str] project: The project associated with the token.
        :param pulumi.Input[_builtins.str] renew_after: Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renew_after`. I.e. if `currentDate - issued_at > renew_after`.
        :param pulumi.Input[_builtins.str] renew_before: Duration to control token silent regeneration based on remaining token lifetime. If `expires_in` is set, the provider will regenerate the token if `expires_at - currentDate < renew_before`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
        :param pulumi.Input[_builtins.str] role: The name of the role in the project associated with the token.
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if expires_at is not None:
            pulumi.set(__self__, "expires_at", expires_at)
        if expires_in is not None:
            pulumi.set(__self__, "expires_in", expires_in)
        if issued_at is not None:
            pulumi.set(__self__, "issued_at", issued_at)
        if jwt is not None:
            pulumi.set(__self__, "jwt", jwt)
        if project is not None:
            pulumi.set(__self__, "project", project)
        if renew_after is not None:
            pulumi.set(__self__, "renew_after", renew_after)
        if renew_before is not None:
            pulumi.set(__self__, "renew_before", renew_before)
        if role is not None:
            pulumi.set(__self__, "role", role)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Description of the token.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        If `expires_in` is set, Unix timestamp upon which the token will expire.
        """
        return pulumi.get(self, "expires_at")

    @expires_at.setter
    def expires_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expires_at", value)

    @_builtins.property
    @pulumi.getter(name="expiresIn")
    def expires_in(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
        """
        return pulumi.get(self, "expires_in")

    @expires_in.setter
    def expires_in(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "expires_in", value)

    @_builtins.property
    @pulumi.getter(name="issuedAt")
    def issued_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unix timestamp at which the token was issued.
        """
        return pulumi.get(self, "issued_at")

    @issued_at.setter
    def issued_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "issued_at", value)

    @_builtins.property
    @pulumi.getter
    def jwt(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The raw JWT.
        """
        return pulumi.get(self, "jwt")

    @jwt.setter
    def jwt(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "jwt", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The project associated with the token.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter(name="renewAfter")
    def renew_after(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renew_after`. I.e. if `currentDate - issued_at > renew_after`.
        """
        return pulumi.get(self, "renew_after")

    @renew_after.setter
    def renew_after(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "renew_after", value)

    @_builtins.property
    @pulumi.getter(name="renewBefore")
    def renew_before(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Duration to control token silent regeneration based on remaining token lifetime. If `expires_in` is set, the provider will regenerate the token if `expires_at - currentDate < renew_before`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
        """
        return pulumi.get(self, "renew_before")

    @renew_before.setter
    def renew_before(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "renew_before", value)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the role in the project associated with the token.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "role", value)


@pulumi.type_token("argocd:index/projectToken:ProjectToken")
class ProjectToken(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.str]] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 renew_after: pulumi.Input[Optional[_builtins.str]] = None,
                 renew_before: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manages ArgoCD project role JWT tokens. See [Project Roles](https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-roles) for more info.

        > **Security Notice** The JWT token generated by this resource is treated as sensitive and, thus, not displayed in console output. However, it will be stored *unencrypted* in your Terraform state file. Read more about sensitive data handling in the Terraform documentation.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_argocd as argocd

        secret = argocd.ProjectToken("secret",
            project="someproject",
            role="foobar",
            description="short lived token",
            expires_in="1h",
            renew_before="30m")
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the token.
        :param pulumi.Input[_builtins.str] expires_in: Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
        :param pulumi.Input[_builtins.str] project: The project associated with the token.
        :param pulumi.Input[_builtins.str] renew_after: Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renew_after`. I.e. if `currentDate - issued_at > renew_after`.
        :param pulumi.Input[_builtins.str] renew_before: Duration to control token silent regeneration based on remaining token lifetime. If `expires_in` is set, the provider will regenerate the token if `expires_at - currentDate < renew_before`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
        :param pulumi.Input[_builtins.str] role: The name of the role in the project associated with the token.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProjectTokenArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages ArgoCD project role JWT tokens. See [Project Roles](https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-roles) for more info.

        > **Security Notice** The JWT token generated by this resource is treated as sensitive and, thus, not displayed in console output. However, it will be stored *unencrypted* in your Terraform state file. Read more about sensitive data handling in the Terraform documentation.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_argocd as argocd

        secret = argocd.ProjectToken("secret",
            project="someproject",
            role="foobar",
            description="short lived token",
            expires_in="1h",
            renew_before="30m")
        ```


        :param str resource_name: The name of the resource.
        :param ProjectTokenArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProjectTokenArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 expires_in: pulumi.Input[Optional[_builtins.str]] = None,
                 project: pulumi.Input[Optional[_builtins.str]] = None,
                 renew_after: pulumi.Input[Optional[_builtins.str]] = None,
                 renew_before: pulumi.Input[Optional[_builtins.str]] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProjectTokenArgs.__new__(ProjectTokenArgs)

            __props__.__dict__["description"] = description
            __props__.__dict__["expires_in"] = expires_in
            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            __props__.__dict__["renew_after"] = renew_after
            __props__.__dict__["renew_before"] = renew_before
            if role is None and not opts.urn:
                raise TypeError("Missing required property 'role'")
            __props__.__dict__["role"] = role
            __props__.__dict__["expires_at"] = None
            __props__.__dict__["issued_at"] = None
            __props__.__dict__["jwt"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["jwt"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ProjectToken, __self__).__init__(
            'argocd:index/projectToken:ProjectToken',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            expires_at: pulumi.Input[Optional[_builtins.str]] = None,
            expires_in: pulumi.Input[Optional[_builtins.str]] = None,
            issued_at: pulumi.Input[Optional[_builtins.str]] = None,
            jwt: pulumi.Input[Optional[_builtins.str]] = None,
            project: pulumi.Input[Optional[_builtins.str]] = None,
            renew_after: pulumi.Input[Optional[_builtins.str]] = None,
            renew_before: pulumi.Input[Optional[_builtins.str]] = None,
            role: pulumi.Input[Optional[_builtins.str]] = None) -> 'ProjectToken':
        """
        Get an existing ProjectToken resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] description: Description of the token.
        :param pulumi.Input[_builtins.str] expires_at: If `expires_in` is set, Unix timestamp upon which the token will expire.
        :param pulumi.Input[_builtins.str] expires_in: Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
        :param pulumi.Input[_builtins.str] issued_at: Unix timestamp at which the token was issued.
        :param pulumi.Input[_builtins.str] jwt: The raw JWT.
        :param pulumi.Input[_builtins.str] project: The project associated with the token.
        :param pulumi.Input[_builtins.str] renew_after: Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renew_after`. I.e. if `currentDate - issued_at > renew_after`.
        :param pulumi.Input[_builtins.str] renew_before: Duration to control token silent regeneration based on remaining token lifetime. If `expires_in` is set, the provider will regenerate the token if `expires_at - currentDate < renew_before`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
        :param pulumi.Input[_builtins.str] role: The name of the role in the project associated with the token.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProjectTokenState.__new__(_ProjectTokenState)

        __props__.__dict__["description"] = description
        __props__.__dict__["expires_at"] = expires_at
        __props__.__dict__["expires_in"] = expires_in
        __props__.__dict__["issued_at"] = issued_at
        __props__.__dict__["jwt"] = jwt
        __props__.__dict__["project"] = project
        __props__.__dict__["renew_after"] = renew_after
        __props__.__dict__["renew_before"] = renew_before
        __props__.__dict__["role"] = role
        return ProjectToken(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the token.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="expiresAt")
    def expires_at(self) -> pulumi.Output[_builtins.str]:
        """
        If `expires_in` is set, Unix timestamp upon which the token will expire.
        """
        return pulumi.get(self, "expires_at")

    @_builtins.property
    @pulumi.getter(name="expiresIn")
    def expires_in(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
        """
        return pulumi.get(self, "expires_in")

    @_builtins.property
    @pulumi.getter(name="issuedAt")
    def issued_at(self) -> pulumi.Output[_builtins.str]:
        """
        Unix timestamp at which the token was issued.
        """
        return pulumi.get(self, "issued_at")

    @_builtins.property
    @pulumi.getter
    def jwt(self) -> pulumi.Output[_builtins.str]:
        """
        The raw JWT.
        """
        return pulumi.get(self, "jwt")

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Output[_builtins.str]:
        """
        The project associated with the token.
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter(name="renewAfter")
    def renew_after(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renew_after`. I.e. if `currentDate - issued_at > renew_after`.
        """
        return pulumi.get(self, "renew_after")

    @_builtins.property
    @pulumi.getter(name="renewBefore")
    def renew_before(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Duration to control token silent regeneration based on remaining token lifetime. If `expires_in` is set, the provider will regenerate the token if `expires_at - currentDate < renew_before`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
        """
        return pulumi.get(self, "renew_before")

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the role in the project associated with the token.
        """
        return pulumi.get(self, "role")

