// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGitlabCaRef
    {
        /// <summary>
        /// Name of the ConfigMap.
        /// </summary>
        public readonly string ConfigMapName;
        /// <summary>
        /// Key containing information in trusted CA certs.
        /// </summary>
        public readonly string Key;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMergeGeneratorMatrixGeneratorPullRequestGitlabCaRef(
            string configMapName,

            string key)
        {
            ConfigMapName = configMapName;
            Key = key;
        }
    }
}
