// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorGitDirectory
    {
        /// <summary>
        /// Flag indicating whether or not the directory should be excluded when templating.
        /// </summary>
        public readonly bool? Exclude;
        /// <summary>
        /// Path in the repository.
        /// </summary>
        public readonly string Path;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMatrixGeneratorMatrixGeneratorGitDirectory(
            bool? exclude,

            string path)
        {
            Exclude = exclude;
            Path = path;
        }
    }
}
