// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequestAzureDevops
    {
        /// <summary>
        /// The Azure DevOps API URL to talk to. If blank, uses https://dev.azure.com/.
        /// </summary>
        public readonly string? Api;
        /// <summary>
        /// Labels is used to filter the PRs that you want to target.
        /// </summary>
        public readonly ImmutableArray<string> Labels;
        /// <summary>
        /// Azure DevOps org to scan. Required.
        /// </summary>
        public readonly string Organization;
        /// <summary>
        /// Azure DevOps project name to scan. Required.
        /// </summary>
        public readonly string Project;
        /// <summary>
        /// Azure DevOps repo name to scan. Required.
        /// </summary>
        public readonly string Repo;
        /// <summary>
        /// Authentication token reference.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequestAzureDevopsTokenRef? TokenRef;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequestAzureDevops(
            string? api,

            ImmutableArray<string> labels,

            string organization,

            string project,

            string repo,

            Outputs.ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequestAzureDevopsTokenRef? tokenRef)
        {
            Api = api;
            Labels = labels;
            Organization = organization;
            Project = project;
            Repo = repo;
            TokenRef = tokenRef;
        }
    }
}
