// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPullRequestGitlab
    {
        /// <summary>
        /// The GitLab API URL to talk to. If blank, uses https://gitlab.com/.
        /// </summary>
        public readonly string? Api;
        /// <summary>
        /// Reference to a ConfigMap key containing trusted CA certificates for verifying the SCM server's TLS certificate.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPullRequestGitlabCaRef? CaRef;
        /// <summary>
        /// A flag for checking the validity of the SCM's certificates.
        /// </summary>
        public readonly bool? Insecure;
        /// <summary>
        /// Labels is used to filter the PRs that you want to target.
        /// </summary>
        public readonly ImmutableArray<string> Labels;
        /// <summary>
        /// GitLab project to scan.
        /// </summary>
        public readonly string Project;
        /// <summary>
        /// additional MRs filter to get only those with a certain state. Default:  "" (all states).
        /// </summary>
        public readonly string? PullRequestState;
        /// <summary>
        /// Authentication token reference.
        /// </summary>
        public readonly Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPullRequestGitlabTokenRef? TokenRef;

        [OutputConstructor]
        private ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPullRequestGitlab(
            string? api,

            Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPullRequestGitlabCaRef? caRef,

            bool? insecure,

            ImmutableArray<string> labels,

            string project,

            string? pullRequestState,

            Outputs.ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorPullRequestGitlabTokenRef? tokenRef)
        {
            Api = api;
            CaRef = caRef;
            Insecure = insecure;
            Labels = labels;
            Project = project;
            PullRequestState = pullRequestState;
            TokenRef = tokenRef;
        }
    }
}
