// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class GetApplicationStatusResourceResult
    {
        /// <summary>
        /// The Kubernetes resource Group.
        /// </summary>
        public readonly string Group;
        /// <summary>
        /// Resource health status.
        /// </summary>
        public readonly Outputs.GetApplicationStatusResourceHealthResult Health;
        /// <summary>
        /// Indicates whether or not this resource has a hook annotation.
        /// </summary>
        public readonly bool Hook;
        /// <summary>
        /// The Kubernetes resource Kind.
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// The Kubernetes resource Name.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The Kubernetes resource Namespace.
        /// </summary>
        public readonly string Namespace;
        /// <summary>
        /// Indicates if the resources requires pruning or not.
        /// </summary>
        public readonly bool RequiresPruning;
        /// <summary>
        /// Resource sync status.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Sync wave.
        /// </summary>
        public readonly int SyncWave;
        /// <summary>
        /// The Kubernetes resource Version.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetApplicationStatusResourceResult(
            string group,

            Outputs.GetApplicationStatusResourceHealthResult health,

            bool hook,

            string kind,

            string name,

            string @namespace,

            bool requiresPruning,

            string status,

            int syncWave,

            string version)
        {
            Group = group;
            Health = health;
            Hook = hook;
            Kind = kind;
            Name = name;
            Namespace = @namespace;
            RequiresPruning = requiresPruning;
            Status = status;
            SyncWave = syncWave;
            Version = version;
        }
    }
}
