// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class GetApplicationSpecSourcePluginParameterResult
    {
        /// <summary>
        /// Value of an array type parameters.
        /// </summary>
        public readonly ImmutableArray<string> Arrays;
        /// <summary>
        /// Value of a map type parameters.
        /// </summary>
        public readonly ImmutableDictionary<string, string> Map;
        /// <summary>
        /// Name identifying a parameters.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Value of a string type parameters.
        /// </summary>
        public readonly string String;

        [OutputConstructor]
        private GetApplicationSpecSourcePluginParameterResult(
            ImmutableArray<string> arrays,

            ImmutableDictionary<string, string> map,

            string name,

            string @string)
        {
            Arrays = arrays;
            Map = map;
            Name = name;
            String = @string;
        }
    }
}
