// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class GetApplicationSpecSyncPolicyResult
    {
        /// <summary>
        /// Whether to automatically keep an application synced to the target revision.
        /// </summary>
        public readonly Outputs.GetApplicationSpecSyncPolicyAutomatedResult Automated;
        /// <summary>
        /// Controls failed sync retry behavior.
        /// </summary>
        public readonly Outputs.GetApplicationSpecSyncPolicyRetryResult Retry;
        /// <summary>
        /// List of sync options. More info: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/.
        /// </summary>
        public readonly ImmutableArray<string> SyncOptions;

        [OutputConstructor]
        private GetApplicationSpecSyncPolicyResult(
            Outputs.GetApplicationSpecSyncPolicyAutomatedResult automated,

            Outputs.GetApplicationSpecSyncPolicyRetryResult retry,

            ImmutableArray<string> syncOptions)
        {
            Automated = automated;
            Retry = retry;
            SyncOptions = syncOptions;
        }
    }
}
