// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class GetApplicationStatusResourceHealthResult
    {
        /// <summary>
        /// Human-readable informational message describing the health status.
        /// </summary>
        public readonly string Message;
        /// <summary>
        /// Status code of the application or resource.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetApplicationStatusResourceHealthResult(
            string message,

            string status)
        {
            Message = message;
            Status = status;
        }
    }
}
