// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class GetApplicationStatusSyncResult
    {
        /// <summary>
        /// Information about the revision(s) the comparison has been performed to.
        /// </summary>
        public readonly ImmutableArray<string> Revisions;
        /// <summary>
        /// Sync state of the comparison.
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private GetApplicationStatusSyncResult(
            ImmutableArray<string> revisions,

            string status)
        {
            Revisions = revisions;
            Status = status;
        }
    }
}
