// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Outputs
{

    [OutputType]
    public sealed class GetApplicationStatusResult
    {
        /// <summary>
        /// List of currently observed application conditions.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetApplicationStatusConditionResult> Conditions;
        /// <summary>
        /// Application's current health status.
        /// </summary>
        public readonly Outputs.GetApplicationStatusHealthResult Health;
        /// <summary>
        /// Information about any ongoing operations, such as a sync.
        /// </summary>
        public readonly Outputs.GetApplicationStatusOperationStateResult OperationState;
        /// <summary>
        /// When the application state was reconciled using the latest git version.
        /// </summary>
        public readonly string ReconciledAt;
        /// <summary>
        /// List of Kubernetes resources managed by this application.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetApplicationStatusResourceResult> Resources;
        /// <summary>
        /// List of URLs and container images used by this application.
        /// </summary>
        public readonly Outputs.GetApplicationStatusSummaryResult Summary;
        /// <summary>
        /// Application's current sync status
        /// </summary>
        public readonly Outputs.GetApplicationStatusSyncResult Sync;

        [OutputConstructor]
        private GetApplicationStatusResult(
            ImmutableArray<Outputs.GetApplicationStatusConditionResult> conditions,

            Outputs.GetApplicationStatusHealthResult health,

            Outputs.GetApplicationStatusOperationStateResult operationState,

            string reconciledAt,

            ImmutableArray<Outputs.GetApplicationStatusResourceResult> resources,

            Outputs.GetApplicationStatusSummaryResult summary,

            Outputs.GetApplicationStatusSyncResult sync)
        {
            Conditions = conditions;
            Health = health;
            OperationState = operationState;
            ReconciledAt = reconciledAt;
            Resources = resources;
            Summary = summary;
            Sync = sync;
        }
    }
}
