// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ProjectSpec
    {
        /// <summary>
        /// Blacklisted cluster level resources.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecClusterResourceBlacklist> ClusterResourceBlacklists;
        /// <summary>
        /// Whitelisted cluster level resources.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecClusterResourceWhitelist> ClusterResourceWhitelists;
        /// <summary>
        /// Project description.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Service accounts to be impersonated for the application sync operation for each destination.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecDestinationServiceAccount> DestinationServiceAccounts;
        /// <summary>
        /// Destinations available for deployment.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecDestination> Destinations;
        /// <summary>
        /// Blacklisted namespace level resources.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecNamespaceResourceBlacklist> NamespaceResourceBlacklists;
        /// <summary>
        /// Whitelisted namespace level resources.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecNamespaceResourceWhitelist> NamespaceResourceWhitelists;
        /// <summary>
        /// Configuration for orphaned resources tracking.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecOrphanedResource> OrphanedResources;
        /// <summary>
        /// Project roles.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecRole> Roles;
        /// <summary>
        /// Signature keys for verifying the integrity of applications.
        /// </summary>
        public readonly ImmutableArray<string> SignatureKeys;
        /// <summary>
        /// List of source namespaces for applications.
        /// </summary>
        public readonly ImmutableArray<string> SourceNamespaces;
        /// <summary>
        /// List of repositories from which applications may be created.
        /// </summary>
        public readonly ImmutableArray<string> SourceRepos;
        /// <summary>
        /// Controls when sync operations are allowed for the project.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecSyncWindow> SyncWindows;

        [OutputConstructor]
        private ProjectSpec(
            ImmutableArray<Outputs.ProjectSpecClusterResourceBlacklist> clusterResourceBlacklists,

            ImmutableArray<Outputs.ProjectSpecClusterResourceWhitelist> clusterResourceWhitelists,

            string? description,

            ImmutableArray<Outputs.ProjectSpecDestinationServiceAccount> destinationServiceAccounts,

            ImmutableArray<Outputs.ProjectSpecDestination> destinations,

            ImmutableArray<Outputs.ProjectSpecNamespaceResourceBlacklist> namespaceResourceBlacklists,

            ImmutableArray<Outputs.ProjectSpecNamespaceResourceWhitelist> namespaceResourceWhitelists,

            ImmutableArray<Outputs.ProjectSpecOrphanedResource> orphanedResources,

            ImmutableArray<Outputs.ProjectSpecRole> roles,

            ImmutableArray<string> signatureKeys,

            ImmutableArray<string> sourceNamespaces,

            ImmutableArray<string> sourceRepos,

            ImmutableArray<Outputs.ProjectSpecSyncWindow> syncWindows)
        {
            ClusterResourceBlacklists = clusterResourceBlacklists;
            ClusterResourceWhitelists = clusterResourceWhitelists;
            Description = description;
            DestinationServiceAccounts = destinationServiceAccounts;
            Destinations = destinations;
            NamespaceResourceBlacklists = namespaceResourceBlacklists;
            NamespaceResourceWhitelists = namespaceResourceWhitelists;
            OrphanedResources = orphanedResources;
            Roles = roles;
            SignatureKeys = signatureKeys;
            SourceNamespaces = sourceNamespaces;
            SourceRepos = sourceRepos;
            SyncWindows = syncWindows;
        }
    }
}
