// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ProjectSpecOrphanedResourceIgnore
    {
        /// <summary>
        /// The Kubernetes resource Group to match for.
        /// </summary>
        public readonly string? Group;
        /// <summary>
        /// The Kubernetes resource Kind to match for.
        /// </summary>
        public readonly string? Kind;
        /// <summary>
        /// The Kubernetes resource name to match for.
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private ProjectSpecOrphanedResourceIgnore(
            string? group,

            string? kind,

            string? name)
        {
            Group = group;
            Kind = kind;
            Name = name;
        }
    }
}
