// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ProjectSpecRole
    {
        /// <summary>
        /// Description of the role.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// List of OIDC group claims bound to this role.
        /// </summary>
        public readonly ImmutableArray<string> Groups;
        /// <summary>
        /// List of JWT tokens issued for this role.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecRoleJwtToken> JwtTokens;
        /// <summary>
        /// The name of the role.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// List of casbin formatted strings that define access policies for the role in the project. For more information, see the [ArgoCD RBAC reference](https://argoproj.github.io/argo-cd/operator-manual/rbac/#rbac-permission-structure).
        /// </summary>
        public readonly ImmutableArray<string> Policies;

        [OutputConstructor]
        private ProjectSpecRole(
            string? description,

            ImmutableArray<string> groups,

            ImmutableArray<Outputs.ProjectSpecRoleJwtToken> jwtTokens,

            string name,

            ImmutableArray<string> policies)
        {
            Description = description;
            Groups = groups;
            JwtTokens = jwtTokens;
            Name = name;
            Policies = policies;
        }
    }
}
