// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ProjectSpecRoleJwtToken
    {
        /// <summary>
        /// Token expiration (timestamp).
        /// </summary>
        public readonly int? Exp;
        /// <summary>
        /// Token issued at (timestamp).
        /// </summary>
        public readonly int Iat;
        /// <summary>
        /// Token identifier.
        /// </summary>
        public readonly string? Id;

        [OutputConstructor]
        private ProjectSpecRoleJwtToken(
            int? exp,

            int iat,

            string? id)
        {
            Exp = exp;
            Iat = iat;
            Id = id;
        }
    }
}
