// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Outputs
{

    [OutputType]
    public sealed class ProjectSpecOrphanedResource
    {
        /// <summary>
        /// List of resources to ignore during orphaned resources detection.
        /// </summary>
        public readonly ImmutableArray<Outputs.ProjectSpecOrphanedResourceIgnore> Ignores;
        /// <summary>
        /// Whether a warning condition should be created for apps which have orphaned resources.
        /// </summary>
        public readonly bool? Warn;

        [OutputConstructor]
        private ProjectSpecOrphanedResource(
            ImmutableArray<Outputs.ProjectSpecOrphanedResourceIgnore> ignores,

            bool? warn)
        {
            Ignores = ignores;
            Warn = warn;
        }
    }
}
