// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package argocd

import (
	"context"
	"reflect"

	"github.com/Three141/pulumi-argocd/sdk/go/argocd/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Reads an existing ArgoCD application.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Three141/pulumi-argocd/sdk/go/argocd"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := argocd.GetApplication(ctx, &argocd.GetApplicationArgs{
//				Metadata: argocd.GetApplicationMetadata{
//					Name:      "foo",
//					Namespace: "argocd",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetApplication(ctx *pulumi.Context, args *GetApplicationArgs, opts ...pulumi.InvokeOption) (*GetApplicationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetApplicationResult
	err := ctx.Invoke("argocd:index/getApplication:getApplication", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApplication.
type GetApplicationArgs struct {
	// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
	Metadata GetApplicationMetadata `pulumi:"metadata"`
}

// A collection of values returned by getApplication.
type GetApplicationResult struct {
	// ArgoCD application identifier
	Id string `pulumi:"id"`
	// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
	Metadata GetApplicationMetadata `pulumi:"metadata"`
	// The application specification.
	Spec GetApplicationSpec `pulumi:"spec"`
	// Status information for the application.
	Status GetApplicationStatus `pulumi:"status"`
}

func GetApplicationOutput(ctx *pulumi.Context, args GetApplicationOutputArgs, opts ...pulumi.InvokeOption) GetApplicationResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetApplicationResultOutput, error) {
			args := v.(GetApplicationArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("argocd:index/getApplication:getApplication", args, GetApplicationResultOutput{}, options).(GetApplicationResultOutput), nil
		}).(GetApplicationResultOutput)
}

// A collection of arguments for invoking getApplication.
type GetApplicationOutputArgs struct {
	// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
	Metadata GetApplicationMetadataInput `pulumi:"metadata"`
}

func (GetApplicationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetApplicationArgs)(nil)).Elem()
}

// A collection of values returned by getApplication.
type GetApplicationResultOutput struct{ *pulumi.OutputState }

func (GetApplicationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetApplicationResult)(nil)).Elem()
}

func (o GetApplicationResultOutput) ToGetApplicationResultOutput() GetApplicationResultOutput {
	return o
}

func (o GetApplicationResultOutput) ToGetApplicationResultOutputWithContext(ctx context.Context) GetApplicationResultOutput {
	return o
}

// ArgoCD application identifier
func (o GetApplicationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicationResult) string { return v.Id }).(pulumi.StringOutput)
}

// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
func (o GetApplicationResultOutput) Metadata() GetApplicationMetadataOutput {
	return o.ApplyT(func(v GetApplicationResult) GetApplicationMetadata { return v.Metadata }).(GetApplicationMetadataOutput)
}

// The application specification.
func (o GetApplicationResultOutput) Spec() GetApplicationSpecOutput {
	return o.ApplyT(func(v GetApplicationResult) GetApplicationSpec { return v.Spec }).(GetApplicationSpecOutput)
}

// Status information for the application.
func (o GetApplicationResultOutput) Status() GetApplicationStatusOutput {
	return o.ApplyT(func(v GetApplicationResult) GetApplicationStatus { return v.Status }).(GetApplicationStatusOutput)
}

func init() {
	pulumi.RegisterOutputType(GetApplicationResultOutput{})
}
