// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package argocd

import (
	"context"
	"reflect"

	"github.com/Three141/pulumi-argocd/sdk/go/argocd/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Reads an existing ArgoCD application.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/Three141/pulumi-argocd/sdk/go/argocd"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := argocd.LookupApplication(ctx, &argocd.LookupApplicationArgs{
//				Metadata: argocd.GetApplicationMetadata{
//					Name:      "foo",
//					Namespace: "argocd",
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupApplication(ctx *pulumi.Context, args *LookupApplicationArgs, opts ...pulumi.InvokeOption) (*LookupApplicationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupApplicationResult
	err := ctx.Invoke("argocd:index/getApplication:getApplication", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApplication.
type LookupApplicationArgs struct {
	// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
	Metadata GetApplicationMetadata `pulumi:"metadata"`
}

// A collection of values returned by getApplication.
type LookupApplicationResult struct {
	// ArgoCD application identifier
	Id string `pulumi:"id"`
	// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
	Metadata GetApplicationMetadata `pulumi:"metadata"`
	// The application specification.
	Spec GetApplicationSpec `pulumi:"spec"`
	// Status information for the application.
	Status GetApplicationStatus `pulumi:"status"`
}

func LookupApplicationOutput(ctx *pulumi.Context, args LookupApplicationOutputArgs, opts ...pulumi.InvokeOption) LookupApplicationResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupApplicationResultOutput, error) {
			args := v.(LookupApplicationArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("argocd:index/getApplication:getApplication", args, LookupApplicationResultOutput{}, options).(LookupApplicationResultOutput), nil
		}).(LookupApplicationResultOutput)
}

// A collection of arguments for invoking getApplication.
type LookupApplicationOutputArgs struct {
	// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
	Metadata GetApplicationMetadataInput `pulumi:"metadata"`
}

func (LookupApplicationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApplicationArgs)(nil)).Elem()
}

// A collection of values returned by getApplication.
type LookupApplicationResultOutput struct{ *pulumi.OutputState }

func (LookupApplicationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApplicationResult)(nil)).Elem()
}

func (o LookupApplicationResultOutput) ToLookupApplicationResultOutput() LookupApplicationResultOutput {
	return o
}

func (o LookupApplicationResultOutput) ToLookupApplicationResultOutputWithContext(ctx context.Context) LookupApplicationResultOutput {
	return o
}

// ArgoCD application identifier
func (o LookupApplicationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApplicationResult) string { return v.Id }).(pulumi.StringOutput)
}

// Standard Kubernetes object metadata. For more info see the [Kubernetes reference](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata).
func (o LookupApplicationResultOutput) Metadata() GetApplicationMetadataOutput {
	return o.ApplyT(func(v LookupApplicationResult) GetApplicationMetadata { return v.Metadata }).(GetApplicationMetadataOutput)
}

// The application specification.
func (o LookupApplicationResultOutput) Spec() GetApplicationSpecOutput {
	return o.ApplyT(func(v LookupApplicationResult) GetApplicationSpec { return v.Spec }).(GetApplicationSpecOutput)
}

// Status information for the application.
func (o LookupApplicationResultOutput) Status() GetApplicationStatusOutput {
	return o.ApplyT(func(v LookupApplicationResult) GetApplicationStatus { return v.Status }).(GetApplicationStatusOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApplicationResultOutput{})
}
