// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequestGitlabCaRefArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the ConfigMap.
        /// </summary>
        [Input("configMapName", required: true)]
        public Input<string> ConfigMapName { get; set; } = null!;

        /// <summary>
        /// Key containing information in trusted CA certs.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        public ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequestGitlabCaRefArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequestGitlabCaRefArgs Empty => new ApplicationSetSpecGeneratorMatrixGeneratorMergeGeneratorPullRequestGitlabCaRefArgs();
    }
}
