// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorPullRequestAzureDevopsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Azure DevOps API URL to talk to. If blank, uses https://dev.azure.com/.
        /// </summary>
        [Input("api")]
        public Input<string>? Api { get; set; }

        [Input("labels")]
        private InputList<string>? _labels;

        /// <summary>
        /// Labels is used to filter the PRs that you want to target.
        /// </summary>
        public InputList<string> Labels
        {
            get => _labels ?? (_labels = new InputList<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Azure DevOps org to scan. Required.
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        /// <summary>
        /// Azure DevOps project name to scan. Required.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        /// <summary>
        /// Azure DevOps repo name to scan. Required.
        /// </summary>
        [Input("repo", required: true)]
        public Input<string> Repo { get; set; } = null!;

        /// <summary>
        /// Authentication token reference.
        /// </summary>
        [Input("tokenRef")]
        public Input<Inputs.ApplicationSetSpecGeneratorPullRequestAzureDevopsTokenRefArgs>? TokenRef { get; set; }

        public ApplicationSetSpecGeneratorPullRequestAzureDevopsArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorPullRequestAzureDevopsArgs Empty => new ApplicationSetSpecGeneratorPullRequestAzureDevopsArgs();
    }
}
