// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Argocd.Inputs
{

    public sealed class ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorClusterTemplateSpecInfoGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the information.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Value of the information.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorClusterTemplateSpecInfoGetArgs()
        {
        }
        public static new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorClusterTemplateSpecInfoGetArgs Empty => new ApplicationSetSpecGeneratorMergeGeneratorMergeGeneratorClusterTemplateSpecInfoGetArgs();
    }
}
