// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class GetApplicationMetadataArgs : global::Pulumi.InvokeArgs
    {
        [Input("annotations", required: true)]
        private Dictionary<string, string>? _annotations;

        /// <summary>
        /// An unstructured key value map stored with the applications.argoproj.io that may be used to store arbitrary metadata. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
        /// </summary>
        public Dictionary<string, string> Annotations
        {
            get => _annotations ?? (_annotations = new Dictionary<string, string>());
            set => _annotations = value;
        }

        /// <summary>
        /// A sequence number representing a specific generation of the desired state.
        /// </summary>
        [Input("generation", required: true)]
        public int Generation { get; set; }

        [Input("labels", required: true)]
        private Dictionary<string, string>? _labels;

        /// <summary>
        /// Map of string keys and values that can be used to organize and categorize (scope and select) the applications.argoproj.io. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
        /// </summary>
        public Dictionary<string, string> Labels
        {
            get => _labels ?? (_labels = new Dictionary<string, string>());
            set => _labels = value;
        }

        /// <summary>
        /// Name of the applications.argoproj.io, must be unique. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// Namespace of the applications.argoproj.io, must be unique. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
        /// </summary>
        [Input("namespace", required: true)]
        public string Namespace { get; set; } = null!;

        /// <summary>
        /// An opaque value that represents the internal version of this applications.argoproj.io that can be used by clients to determine when the applications.argoproj.io has changed. Read more: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
        /// </summary>
        [Input("resourceVersion", required: true)]
        public string ResourceVersion { get; set; } = null!;

        /// <summary>
        /// The unique in time and space value for this applications.argoproj.io. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
        /// </summary>
        [Input("uid", required: true)]
        public string Uid { get; set; } = null!;

        public GetApplicationMetadataArgs()
        {
        }
        public static new GetApplicationMetadataArgs Empty => new GetApplicationMetadataArgs();
    }
}
