// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ProjectSpecOrphanedResourcesIgnoreGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Kubernetes resource Group to match for.
        /// </summary>
        [Input("group")]
        public Input<string>? Group { get; set; }

        /// <summary>
        /// The Kubernetes resource Kind to match for.
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// The Kubernetes resource name to match for.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public ProjectSpecOrphanedResourcesIgnoreGetArgs()
        {
        }
        public static new ProjectSpecOrphanedResourcesIgnoreGetArgs Empty => new ProjectSpecOrphanedResourcesIgnoreGetArgs();
    }
}
