// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ProjectSpecDestinationServiceAccountGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Used for impersonation during the sync operation
        /// </summary>
        [Input("defaultServiceAccount", required: true)]
        public Input<string> DefaultServiceAccount { get; set; } = null!;

        /// <summary>
        /// Specifies the target namespace for the application's resources.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        /// <summary>
        /// Specifies the URL of the target cluster's Kubernetes control plane API.
        /// </summary>
        [Input("server")]
        public Input<string>? Server { get; set; }

        public ProjectSpecDestinationServiceAccountGetArgs()
        {
        }
        public static new ProjectSpecDestinationServiceAccountGetArgs Empty => new ProjectSpecDestinationServiceAccountGetArgs();
    }
}
