// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ProjectSpecRoleJwtTokenArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Token expiration (timestamp).
        /// </summary>
        [Input("exp")]
        public Input<int>? Exp { get; set; }

        /// <summary>
        /// Token issued at (timestamp).
        /// </summary>
        [Input("iat", required: true)]
        public Input<int> Iat { get; set; } = null!;

        /// <summary>
        /// Token identifier.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        public ProjectSpecRoleJwtTokenArgs()
        {
        }
        public static new ProjectSpecRoleJwtTokenArgs Empty => new ProjectSpecRoleJwtTokenArgs();
    }
}
