// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ProjectSpecOrphanedResourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("ignores")]
        private InputList<Inputs.ProjectSpecOrphanedResourceIgnoreArgs>? _ignores;

        /// <summary>
        /// List of resources to ignore during orphaned resources detection.
        /// </summary>
        public InputList<Inputs.ProjectSpecOrphanedResourceIgnoreArgs> Ignores
        {
            get => _ignores ?? (_ignores = new InputList<Inputs.ProjectSpecOrphanedResourceIgnoreArgs>());
            set => _ignores = value;
        }

        /// <summary>
        /// Whether a warning condition should be created for apps which have orphaned resources.
        /// </summary>
        [Input("warn")]
        public Input<bool>? Warn { get; set; }

        public ProjectSpecOrphanedResourceArgs()
        {
        }
        public static new ProjectSpecOrphanedResourceArgs Empty => new ProjectSpecOrphanedResourceArgs();
    }
}
