// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ProjectSpecDestinationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the destination cluster which can be used instead of server.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Target namespace for applications' resources.
        /// </summary>
        [Input("namespace", required: true)]
        public Input<string> Namespace { get; set; } = null!;

        /// <summary>
        /// URL of the target cluster and must be set to the Kubernetes control plane API.
        /// </summary>
        [Input("server")]
        public Input<string>? Server { get; set; }

        public ProjectSpecDestinationArgs()
        {
        }
        public static new ProjectSpecDestinationArgs Empty => new ProjectSpecDestinationArgs();
    }
}
