// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Three14.Argocd.Inputs
{

    public sealed class ProjectSpecGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("clusterResourceBlacklists")]
        private InputList<Inputs.ProjectSpecClusterResourceBlacklistGetArgs>? _clusterResourceBlacklists;

        /// <summary>
        /// Blacklisted cluster level resources.
        /// </summary>
        public InputList<Inputs.ProjectSpecClusterResourceBlacklistGetArgs> ClusterResourceBlacklists
        {
            get => _clusterResourceBlacklists ?? (_clusterResourceBlacklists = new InputList<Inputs.ProjectSpecClusterResourceBlacklistGetArgs>());
            set => _clusterResourceBlacklists = value;
        }

        [Input("clusterResourceWhitelists")]
        private InputList<Inputs.ProjectSpecClusterResourceWhitelistGetArgs>? _clusterResourceWhitelists;

        /// <summary>
        /// Whitelisted cluster level resources.
        /// </summary>
        public InputList<Inputs.ProjectSpecClusterResourceWhitelistGetArgs> ClusterResourceWhitelists
        {
            get => _clusterResourceWhitelists ?? (_clusterResourceWhitelists = new InputList<Inputs.ProjectSpecClusterResourceWhitelistGetArgs>());
            set => _clusterResourceWhitelists = value;
        }

        /// <summary>
        /// Project description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("destinationServiceAccounts")]
        private InputList<Inputs.ProjectSpecDestinationServiceAccountGetArgs>? _destinationServiceAccounts;

        /// <summary>
        /// Service accounts to be impersonated for the application sync operation for each destination.
        /// </summary>
        public InputList<Inputs.ProjectSpecDestinationServiceAccountGetArgs> DestinationServiceAccounts
        {
            get => _destinationServiceAccounts ?? (_destinationServiceAccounts = new InputList<Inputs.ProjectSpecDestinationServiceAccountGetArgs>());
            set => _destinationServiceAccounts = value;
        }

        [Input("destinations")]
        private InputList<Inputs.ProjectSpecDestinationGetArgs>? _destinations;

        /// <summary>
        /// Destinations available for deployment.
        /// </summary>
        public InputList<Inputs.ProjectSpecDestinationGetArgs> Destinations
        {
            get => _destinations ?? (_destinations = new InputList<Inputs.ProjectSpecDestinationGetArgs>());
            set => _destinations = value;
        }

        [Input("namespaceResourceBlacklists")]
        private InputList<Inputs.ProjectSpecNamespaceResourceBlacklistGetArgs>? _namespaceResourceBlacklists;

        /// <summary>
        /// Blacklisted namespace level resources.
        /// </summary>
        public InputList<Inputs.ProjectSpecNamespaceResourceBlacklistGetArgs> NamespaceResourceBlacklists
        {
            get => _namespaceResourceBlacklists ?? (_namespaceResourceBlacklists = new InputList<Inputs.ProjectSpecNamespaceResourceBlacklistGetArgs>());
            set => _namespaceResourceBlacklists = value;
        }

        [Input("namespaceResourceWhitelists")]
        private InputList<Inputs.ProjectSpecNamespaceResourceWhitelistGetArgs>? _namespaceResourceWhitelists;

        /// <summary>
        /// Whitelisted namespace level resources.
        /// </summary>
        public InputList<Inputs.ProjectSpecNamespaceResourceWhitelistGetArgs> NamespaceResourceWhitelists
        {
            get => _namespaceResourceWhitelists ?? (_namespaceResourceWhitelists = new InputList<Inputs.ProjectSpecNamespaceResourceWhitelistGetArgs>());
            set => _namespaceResourceWhitelists = value;
        }

        [Input("orphanedResources")]
        private InputList<Inputs.ProjectSpecOrphanedResourceGetArgs>? _orphanedResources;

        /// <summary>
        /// Configuration for orphaned resources tracking.
        /// </summary>
        public InputList<Inputs.ProjectSpecOrphanedResourceGetArgs> OrphanedResources
        {
            get => _orphanedResources ?? (_orphanedResources = new InputList<Inputs.ProjectSpecOrphanedResourceGetArgs>());
            set => _orphanedResources = value;
        }

        [Input("roles")]
        private InputList<Inputs.ProjectSpecRoleGetArgs>? _roles;

        /// <summary>
        /// Project roles.
        /// </summary>
        public InputList<Inputs.ProjectSpecRoleGetArgs> Roles
        {
            get => _roles ?? (_roles = new InputList<Inputs.ProjectSpecRoleGetArgs>());
            set => _roles = value;
        }

        [Input("signatureKeys")]
        private InputList<string>? _signatureKeys;

        /// <summary>
        /// Signature keys for verifying the integrity of applications.
        /// </summary>
        public InputList<string> SignatureKeys
        {
            get => _signatureKeys ?? (_signatureKeys = new InputList<string>());
            set => _signatureKeys = value;
        }

        [Input("sourceNamespaces")]
        private InputList<string>? _sourceNamespaces;

        /// <summary>
        /// List of source namespaces for applications.
        /// </summary>
        public InputList<string> SourceNamespaces
        {
            get => _sourceNamespaces ?? (_sourceNamespaces = new InputList<string>());
            set => _sourceNamespaces = value;
        }

        [Input("sourceRepos")]
        private InputList<string>? _sourceRepos;

        /// <summary>
        /// List of repositories from which applications may be created.
        /// </summary>
        public InputList<string> SourceRepos
        {
            get => _sourceRepos ?? (_sourceRepos = new InputList<string>());
            set => _sourceRepos = value;
        }

        [Input("syncWindows")]
        private InputList<Inputs.ProjectSpecSyncWindowGetArgs>? _syncWindows;

        /// <summary>
        /// Controls when sync operations are allowed for the project.
        /// </summary>
        public InputList<Inputs.ProjectSpecSyncWindowGetArgs> SyncWindows
        {
            get => _syncWindows ?? (_syncWindows = new InputList<Inputs.ProjectSpecSyncWindowGetArgs>());
            set => _syncWindows = value;
        }

        public ProjectSpecGetArgs()
        {
        }
        public static new ProjectSpecGetArgs Empty => new ProjectSpecGetArgs();
    }
}
