// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages ArgoCD project role JWT tokens. See [Project Roles](https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#project-roles) for more info.
 *
 * > **Security Notice** The JWT token generated by this resource is treated as sensitive and, thus, not displayed in console output. However, it will be stored *unencrypted* in your Terraform state file. Read more about sensitive data handling in the Terraform documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as argocd from "@three14/pulumi-argocd";
 *
 * const secret = new argocd.ProjectToken("secret", {
 *     project: "someproject",
 *     role: "foobar",
 *     description: "short lived token",
 *     expiresIn: "1h",
 *     renewBefore: "30m",
 * });
 * ```
 */
export class ProjectToken extends pulumi.CustomResource {
    /**
     * Get an existing ProjectToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectTokenState, opts?: pulumi.CustomResourceOptions): ProjectToken {
        return new ProjectToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'argocd:index/projectToken:ProjectToken';

    /**
     * Returns true if the given object is an instance of ProjectToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectToken.__pulumiType;
    }

    /**
     * Description of the token.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * If `expiresIn` is set, Unix timestamp upon which the token will expire.
     */
    declare public /*out*/ readonly expiresAt: pulumi.Output<string>;
    /**
     * Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
     */
    declare public readonly expiresIn: pulumi.Output<string | undefined>;
    /**
     * Unix timestamp at which the token was issued.
     */
    declare public /*out*/ readonly issuedAt: pulumi.Output<string>;
    /**
     * The raw JWT.
     */
    declare public /*out*/ readonly jwt: pulumi.Output<string>;
    /**
     * The project associated with the token.
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renewAfter`. I.e. if `currentDate - issuedAt > renewAfter`.
     */
    declare public readonly renewAfter: pulumi.Output<string | undefined>;
    /**
     * Duration to control token silent regeneration based on remaining token lifetime. If `expiresIn` is set, the provider will regenerate the token if `expiresAt - currentDate < renewBefore`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
     */
    declare public readonly renewBefore: pulumi.Output<string | undefined>;
    /**
     * The name of the role in the project associated with the token.
     */
    declare public readonly role: pulumi.Output<string>;

    /**
     * Create a ProjectToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectTokenArgs | ProjectTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectTokenState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["expiresAt"] = state?.expiresAt;
            resourceInputs["expiresIn"] = state?.expiresIn;
            resourceInputs["issuedAt"] = state?.issuedAt;
            resourceInputs["jwt"] = state?.jwt;
            resourceInputs["project"] = state?.project;
            resourceInputs["renewAfter"] = state?.renewAfter;
            resourceInputs["renewBefore"] = state?.renewBefore;
            resourceInputs["role"] = state?.role;
        } else {
            const args = argsOrState as ProjectTokenArgs | undefined;
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["expiresIn"] = args?.expiresIn;
            resourceInputs["project"] = args?.project;
            resourceInputs["renewAfter"] = args?.renewAfter;
            resourceInputs["renewBefore"] = args?.renewBefore;
            resourceInputs["role"] = args?.role;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["issuedAt"] = undefined /*out*/;
            resourceInputs["jwt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["jwt"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ProjectToken.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProjectToken resources.
 */
export interface ProjectTokenState {
    /**
     * Description of the token.
     */
    description?: pulumi.Input<string>;
    /**
     * If `expiresIn` is set, Unix timestamp upon which the token will expire.
     */
    expiresAt?: pulumi.Input<string>;
    /**
     * Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
     */
    expiresIn?: pulumi.Input<string>;
    /**
     * Unix timestamp at which the token was issued.
     */
    issuedAt?: pulumi.Input<string>;
    /**
     * The raw JWT.
     */
    jwt?: pulumi.Input<string>;
    /**
     * The project associated with the token.
     */
    project?: pulumi.Input<string>;
    /**
     * Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renewAfter`. I.e. if `currentDate - issuedAt > renewAfter`.
     */
    renewAfter?: pulumi.Input<string>;
    /**
     * Duration to control token silent regeneration based on remaining token lifetime. If `expiresIn` is set, the provider will regenerate the token if `expiresAt - currentDate < renewBefore`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
     */
    renewBefore?: pulumi.Input<string>;
    /**
     * The name of the role in the project associated with the token.
     */
    role?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ProjectToken resource.
 */
export interface ProjectTokenArgs {
    /**
     * Description of the token.
     */
    description?: pulumi.Input<string>;
    /**
     * Duration before the token will expire. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. E.g. `30m`, `12h`. Default: No expiration.
     */
    expiresIn?: pulumi.Input<string>;
    /**
     * The project associated with the token.
     */
    project: pulumi.Input<string>;
    /**
     * Duration to control token silent regeneration based on token age. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`. If set, then the token will be regenerated if it is older than `renewAfter`. I.e. if `currentDate - issuedAt > renewAfter`.
     */
    renewAfter?: pulumi.Input<string>;
    /**
     * Duration to control token silent regeneration based on remaining token lifetime. If `expiresIn` is set, the provider will regenerate the token if `expiresAt - currentDate < renewBefore`. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
     */
    renewBefore?: pulumi.Input<string>;
    /**
     * The name of the role in the project associated with the token.
     */
    role: pulumi.Input<string>;
}
