// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages [repositories](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories) within ArgoCD.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as argocd from "@three14/pulumi-argocd";
 *
 * // Public Helm repository
 * const publicNginxHelm = new argocd.Repository("public_nginx_helm", {
 *     repo: "https://helm.nginx.com/stable",
 *     name: "nginx-stable",
 *     type: "helm",
 * });
 * // Public Git repository
 * const publicGit = new argocd.Repository("public_git", {repo: "git@github.com:user/somerepo.git"});
 * // Private Git repository
 * const _private = new argocd.Repository("private", {
 *     repo: "git@private-git-repository.local:somerepo.git",
 *     username: "git",
 *     sshPrivateKey: `-----BEGIN OPENSSH PRIVATE KEY-----
 * foo
 * bar
 * -----END OPENSSH PRIVATE KEY-----`,
 *     insecure: true,
 * });
 * // Repository with proxy configuration
 * const withProxy = new argocd.Repository("with_proxy", {
 *     repo: "https://github.com/example/repo.git",
 *     username: "git",
 *     password: "my-token",
 *     proxy: "http://proxy.example.com:8080",
 *     noProxy: "*.internal.example.com,localhost",
 * });
 * // OCI repository (e.g., for Helm charts stored in OCI registries)
 * const ociRegistry = new argocd.Repository("oci_registry", {
 *     repo: "oci://ghcr.io/argoproj/argo-helm/argo-cd",
 *     name: "argocd-oci",
 *     type: "oci",
 *     username: "my-username",
 *     password: "my-token",
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Repositories can be imported using the repository URL.
 *
 * Note: as the ArgoCD API does not return any sensitive information, a
 * subsequent `pulumi up` should be executed to make the `password`,
 * `sshPrivateKey` and `tlsClientCertKey` attributes converge to their
 * expected values defined within the plan.
 *
 * ```sh
 * $ pulumi import argocd:index/repository:Repository myrepo git@private-git-repository.local:somerepo.git
 * ```
 */
export class Repository extends pulumi.CustomResource {
    /**
     * Get an existing Repository resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryState, opts?: pulumi.CustomResourceOptions): Repository {
        return new Repository(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'argocd:index/repository:Repository';

    /**
     * Returns true if the given object is an instance of Repository.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Repository {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Repository.__pulumiType;
    }

    /**
     * BearerToken contains the bearer token used for Git BitBucket Data Center auth at the repo server
     */
    declare public readonly bearerToken: pulumi.Output<string | undefined>;
    /**
     * Contains information about the current state of connection to the repository server.
     */
    declare public /*out*/ readonly connectionStateStatus: pulumi.Output<string>;
    /**
     * Whether `git-lfs` support should be enabled for this repository.
     */
    declare public readonly enableLfs: pulumi.Output<boolean>;
    /**
     * Whether `helm-oci` support should be enabled for this repository.
     */
    declare public readonly enableOci: pulumi.Output<boolean>;
    /**
     * GitHub API URL for GitHub app authentication.
     */
    declare public readonly githubappEnterpriseBaseUrl: pulumi.Output<string>;
    /**
     * ID of the GitHub app used to access the repo.
     */
    declare public readonly githubappId: pulumi.Output<string>;
    /**
     * The installation ID of the GitHub App used to access the repo.
     */
    declare public readonly githubappInstallationId: pulumi.Output<string>;
    /**
     * Private key data (PEM) for authentication via GitHub app.
     */
    declare public readonly githubappPrivateKey: pulumi.Output<string | undefined>;
    /**
     * Whether credentials were inherited from a credential set.
     */
    declare public /*out*/ readonly inheritedCreds: pulumi.Output<boolean>;
    /**
     * Whether the connection to the repository ignores any errors when verifying TLS certificates or SSH host keys.
     */
    declare public readonly insecure: pulumi.Output<boolean>;
    /**
     * Name to be used for this repo. Only used with Helm repos.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Comma-separated list of hostnames that should be excluded from proxying.
     */
    declare public readonly noProxy: pulumi.Output<string | undefined>;
    /**
     * Password or PAT used for authenticating at the remote repository.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * The project name, in case the repository is project scoped.
     */
    declare public readonly project: pulumi.Output<string | undefined>;
    /**
     * HTTP/HTTPS proxy to access the repository.
     */
    declare public readonly proxy: pulumi.Output<string | undefined>;
    /**
     * URL of the repository.
     */
    declare public readonly repo: pulumi.Output<string>;
    /**
     * PEM data for authenticating at the repo server. Only used with Git repos.
     */
    declare public readonly sshPrivateKey: pulumi.Output<string | undefined>;
    /**
     * TLS client certificate in PEM format for authenticating at the repo server.
     */
    declare public readonly tlsClientCertData: pulumi.Output<string | undefined>;
    /**
     * TLS client certificate private key in PEM format for authenticating at the repo server.
     */
    declare public readonly tlsClientCertKey: pulumi.Output<string | undefined>;
    /**
     * Type of the repo. Can be either `git`, `helm` or `oci`. `git` is assumed if empty or absent.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Whether `Azure-Workload-identity` should be enabled for this repository.
     */
    declare public readonly useAzureWorkloadIdentity: pulumi.Output<boolean>;
    /**
     * Username used for authenticating at the remote repository.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Repository resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryArgs | RepositoryState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryState | undefined;
            resourceInputs["bearerToken"] = state?.bearerToken;
            resourceInputs["connectionStateStatus"] = state?.connectionStateStatus;
            resourceInputs["enableLfs"] = state?.enableLfs;
            resourceInputs["enableOci"] = state?.enableOci;
            resourceInputs["githubappEnterpriseBaseUrl"] = state?.githubappEnterpriseBaseUrl;
            resourceInputs["githubappId"] = state?.githubappId;
            resourceInputs["githubappInstallationId"] = state?.githubappInstallationId;
            resourceInputs["githubappPrivateKey"] = state?.githubappPrivateKey;
            resourceInputs["inheritedCreds"] = state?.inheritedCreds;
            resourceInputs["insecure"] = state?.insecure;
            resourceInputs["name"] = state?.name;
            resourceInputs["noProxy"] = state?.noProxy;
            resourceInputs["password"] = state?.password;
            resourceInputs["project"] = state?.project;
            resourceInputs["proxy"] = state?.proxy;
            resourceInputs["repo"] = state?.repo;
            resourceInputs["sshPrivateKey"] = state?.sshPrivateKey;
            resourceInputs["tlsClientCertData"] = state?.tlsClientCertData;
            resourceInputs["tlsClientCertKey"] = state?.tlsClientCertKey;
            resourceInputs["type"] = state?.type;
            resourceInputs["useAzureWorkloadIdentity"] = state?.useAzureWorkloadIdentity;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as RepositoryArgs | undefined;
            if (args?.repo === undefined && !opts.urn) {
                throw new Error("Missing required property 'repo'");
            }
            resourceInputs["bearerToken"] = args?.bearerToken ? pulumi.secret(args.bearerToken) : undefined;
            resourceInputs["enableLfs"] = args?.enableLfs;
            resourceInputs["enableOci"] = args?.enableOci;
            resourceInputs["githubappEnterpriseBaseUrl"] = args?.githubappEnterpriseBaseUrl;
            resourceInputs["githubappId"] = args?.githubappId;
            resourceInputs["githubappInstallationId"] = args?.githubappInstallationId;
            resourceInputs["githubappPrivateKey"] = args?.githubappPrivateKey ? pulumi.secret(args.githubappPrivateKey) : undefined;
            resourceInputs["insecure"] = args?.insecure;
            resourceInputs["name"] = args?.name;
            resourceInputs["noProxy"] = args?.noProxy;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["project"] = args?.project;
            resourceInputs["proxy"] = args?.proxy;
            resourceInputs["repo"] = args?.repo;
            resourceInputs["sshPrivateKey"] = args?.sshPrivateKey ? pulumi.secret(args.sshPrivateKey) : undefined;
            resourceInputs["tlsClientCertData"] = args?.tlsClientCertData;
            resourceInputs["tlsClientCertKey"] = args?.tlsClientCertKey ? pulumi.secret(args.tlsClientCertKey) : undefined;
            resourceInputs["type"] = args?.type;
            resourceInputs["useAzureWorkloadIdentity"] = args?.useAzureWorkloadIdentity;
            resourceInputs["username"] = args?.username;
            resourceInputs["connectionStateStatus"] = undefined /*out*/;
            resourceInputs["inheritedCreds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["bearerToken", "githubappPrivateKey", "password", "sshPrivateKey", "tlsClientCertKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Repository.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Repository resources.
 */
export interface RepositoryState {
    /**
     * BearerToken contains the bearer token used for Git BitBucket Data Center auth at the repo server
     */
    bearerToken?: pulumi.Input<string>;
    /**
     * Contains information about the current state of connection to the repository server.
     */
    connectionStateStatus?: pulumi.Input<string>;
    /**
     * Whether `git-lfs` support should be enabled for this repository.
     */
    enableLfs?: pulumi.Input<boolean>;
    /**
     * Whether `helm-oci` support should be enabled for this repository.
     */
    enableOci?: pulumi.Input<boolean>;
    /**
     * GitHub API URL for GitHub app authentication.
     */
    githubappEnterpriseBaseUrl?: pulumi.Input<string>;
    /**
     * ID of the GitHub app used to access the repo.
     */
    githubappId?: pulumi.Input<string>;
    /**
     * The installation ID of the GitHub App used to access the repo.
     */
    githubappInstallationId?: pulumi.Input<string>;
    /**
     * Private key data (PEM) for authentication via GitHub app.
     */
    githubappPrivateKey?: pulumi.Input<string>;
    /**
     * Whether credentials were inherited from a credential set.
     */
    inheritedCreds?: pulumi.Input<boolean>;
    /**
     * Whether the connection to the repository ignores any errors when verifying TLS certificates or SSH host keys.
     */
    insecure?: pulumi.Input<boolean>;
    /**
     * Name to be used for this repo. Only used with Helm repos.
     */
    name?: pulumi.Input<string>;
    /**
     * Comma-separated list of hostnames that should be excluded from proxying.
     */
    noProxy?: pulumi.Input<string>;
    /**
     * Password or PAT used for authenticating at the remote repository.
     */
    password?: pulumi.Input<string>;
    /**
     * The project name, in case the repository is project scoped.
     */
    project?: pulumi.Input<string>;
    /**
     * HTTP/HTTPS proxy to access the repository.
     */
    proxy?: pulumi.Input<string>;
    /**
     * URL of the repository.
     */
    repo?: pulumi.Input<string>;
    /**
     * PEM data for authenticating at the repo server. Only used with Git repos.
     */
    sshPrivateKey?: pulumi.Input<string>;
    /**
     * TLS client certificate in PEM format for authenticating at the repo server.
     */
    tlsClientCertData?: pulumi.Input<string>;
    /**
     * TLS client certificate private key in PEM format for authenticating at the repo server.
     */
    tlsClientCertKey?: pulumi.Input<string>;
    /**
     * Type of the repo. Can be either `git`, `helm` or `oci`. `git` is assumed if empty or absent.
     */
    type?: pulumi.Input<string>;
    /**
     * Whether `Azure-Workload-identity` should be enabled for this repository.
     */
    useAzureWorkloadIdentity?: pulumi.Input<boolean>;
    /**
     * Username used for authenticating at the remote repository.
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Repository resource.
 */
export interface RepositoryArgs {
    /**
     * BearerToken contains the bearer token used for Git BitBucket Data Center auth at the repo server
     */
    bearerToken?: pulumi.Input<string>;
    /**
     * Whether `git-lfs` support should be enabled for this repository.
     */
    enableLfs?: pulumi.Input<boolean>;
    /**
     * Whether `helm-oci` support should be enabled for this repository.
     */
    enableOci?: pulumi.Input<boolean>;
    /**
     * GitHub API URL for GitHub app authentication.
     */
    githubappEnterpriseBaseUrl?: pulumi.Input<string>;
    /**
     * ID of the GitHub app used to access the repo.
     */
    githubappId?: pulumi.Input<string>;
    /**
     * The installation ID of the GitHub App used to access the repo.
     */
    githubappInstallationId?: pulumi.Input<string>;
    /**
     * Private key data (PEM) for authentication via GitHub app.
     */
    githubappPrivateKey?: pulumi.Input<string>;
    /**
     * Whether the connection to the repository ignores any errors when verifying TLS certificates or SSH host keys.
     */
    insecure?: pulumi.Input<boolean>;
    /**
     * Name to be used for this repo. Only used with Helm repos.
     */
    name?: pulumi.Input<string>;
    /**
     * Comma-separated list of hostnames that should be excluded from proxying.
     */
    noProxy?: pulumi.Input<string>;
    /**
     * Password or PAT used for authenticating at the remote repository.
     */
    password?: pulumi.Input<string>;
    /**
     * The project name, in case the repository is project scoped.
     */
    project?: pulumi.Input<string>;
    /**
     * HTTP/HTTPS proxy to access the repository.
     */
    proxy?: pulumi.Input<string>;
    /**
     * URL of the repository.
     */
    repo: pulumi.Input<string>;
    /**
     * PEM data for authenticating at the repo server. Only used with Git repos.
     */
    sshPrivateKey?: pulumi.Input<string>;
    /**
     * TLS client certificate in PEM format for authenticating at the repo server.
     */
    tlsClientCertData?: pulumi.Input<string>;
    /**
     * TLS client certificate private key in PEM format for authenticating at the repo server.
     */
    tlsClientCertKey?: pulumi.Input<string>;
    /**
     * Type of the repo. Can be either `git`, `helm` or `oci`. `git` is assumed if empty or absent.
     */
    type?: pulumi.Input<string>;
    /**
     * Whether `Azure-Workload-identity` should be enabled for this repository.
     */
    useAzureWorkloadIdentity?: pulumi.Input<boolean>;
    /**
     * Username used for authenticating at the remote repository.
     */
    username?: pulumi.Input<string>;
}
